[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 200
fuzz = { runs = 50, max_test_rejects = 100_000_000}
no_match_path = "**/{script/}*"
remappings = [
    "lib/accounts-v2/lib/openzeppelin-contracts-upgradeable-v4.9:@openzeppelin/=lib/accounts-v2/lib/openzeppelin-contracts-v4.9/",
    "lib/accounts-v2/lib/merkl-contracts:@openzeppelin/contracts/=lib/accounts-v2/lib/openzeppelin-contracts-v4.9/contracts/",
    "lib/accounts-v2/lib/merkl-contracts:@openzeppelin/contracts-upgradeable/=lib/accounts-v2/lib/openzeppelin-contracts-upgradeable-v4.9/contracts/",
    "lib/accounts-v2/lib/slipstream:@openzeppelin/=lib/accounts-v2/lib/slipstream/lib/openzeppelin-contracts/",
    "lib/accounts-v2/lib/v3-periphery:@openzeppelin/=lib/accounts-v2/lib/openzeppelin-contracts-v3.4/",
    "lib/accounts-v2/lib/swap-router-contracts:@openzeppelin/=lib/accounts-v2/lib/openzeppelin-contracts-v3.4/",
    "lib/accounts-v2/lib/v4-periphery:@openzeppelin/=lib/accounts-v2/lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/",
    "lib/accounts-v2/lib/v4-periphery/lib/v4-core:@openzeppelin/=lib/accounts-v2/lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/",
]
fs_permissions = [{ access = "read", path = "./out"}, { access = "write", path = "./script/out"}]
unchecked_cheatcode_artifacts = true

[profile.lite]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = false
fuzz = { runs = 50, max_test_rejects = 100_000_000}

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[profile.hf]
fuzz = { runs = 2_000, max_test_rejects = 1_000_000_000}

[profile.ci]
fuzz = { runs = 200, max_test_rejects = 100_000_000}
